require_relative 'chess/constants'
require_relative 'chess/square'
require_relative 'chess/board'
require_relative 'chess/path'
require_relative 'chess/piece'
require_relative 'chess/knight'
require_relative 'chess/bishop'
